apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressjs-restapi-deployment
  labels:
    app: expressjs-restapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expressjs-restapi
  template:
    metadata:
      labels:
        app: expressjs-restapi
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: expressjs-restapi
        image: hilmiafifi/expressjs-restapi:latest
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "production"
