apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-express-rest-api
  labels:
    app: project-express-rest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-express-rest-api
  template:
    metadata:
      labels:
        app: project-express-rest-api
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: project-express-rest-api
          image: hilmiafifi/project-express-rest-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: NODE_ENV
              value: "production"
#      imagePullSecrets:
#        - name: hilmiafifi
#      restartPolicy: Always
#  namespace: project-express-rest-api-kubernetes-namespace
---
apiVersion: v1
kind: Service
metadata:
  name: project-express-rest-api
  labels:
    app: project-express-rest-api
spec:
  selector:
    app: project-express-rest-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
