apiVersion: v1
kind: Pod
metadata:
  name: project-express-rest-api-pod
  labels:
    app: project-express-rest-api
spec:
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: project-express-rest-api
    image: hilmiafifi/project-express-rest-api:latest
    ports:
    - containerPort: 8000
    env:
    - name: NODE_ENV
      value: "production"
