apiVersion: v1
kind: Service
metadata:
  name: expressjs-restapi-service
spec:
  selector:
    app: expressjs-restapi
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
