apiVersion: v1
kind: Service
metadata:
  name: project-express-rest-api-service
spec:
  selector:
    app: project-express-rest-api
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
